### PR TITLE
add support for Laravel v10

### PR DESCRIPTION
**Pull request by ankurk91**
## Description

Laravel 10 will be released on 7th Feb 2023

I could not make the Github actions to pull Laravel 10 :(
May be we should add another matrix for Laravel version.

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have made corresponding changes to the documentation

### CODE REVIEW

**Comment by mtawil** [comment]
Hello @jeromegamez, please have a look at this PR.

Laravel 10 is released and we need to upgrade

**Comment by asugai** [comment]
I'm in the same boat - hoping this can be updated quickly

**Comment by jeromegamez** [comment]
I already had a look, I will get to it soon, it's probably a little more than just updating the version constraints. I'm sure you'll stay tuned 😄

**Comment by ankurk91** [comment]
All tests are passing on my local machine with orchestra/testbench v8.0 for this package.

**Comment by jeromegamez** [comment]
Oh, I was wrong, it is as simple as updating the version constraints - I forgot that I changed the Workflows to net use testbench anymore 🙈.

**Comment by jeromegamez** [comment]
Thanks @ankurk91!

**Comment by jeromegamez** [comment]
Dangit, I was wrong again, I should have looked at it on my computer instead of the phone 😂. I'll get to it in the next few hours when I'm at my desk.

**Comment by jeromegamez** [comment]
Here it is: https://github.com/kreait/laravel-firebase/releases/tag/5.1.0

**Comment by asugai** [comment]
thank you @jeromegamez !

**Pull request merged**
